// User Module
export const USER_MODULE_USER_LOGIN_BEGIN = 'USER_MODULE_USER_LOGIN_BEGIN';
export const USER_MODULE_USER_LOGIN_SUCCESS = 'USER_MODULE_USER_LOGIN_SUCCESS';
export const USER_MODULE_USER_LOGIN_FAILURE = 'USER_MODULE_USER_LOGIN_FAILURE';
export const USER_MODULE_USER_LOGOUT_BEGIN = 'USER_MODULE_USER_LOGOUT_BEGIN';
export const USER_MODULE_USER_LOGOUT_SUCCESS = 'USER_MODULE_USER_LOGOUT_SUCCESS';
export const USER_MODULE_USER_LOGOUT_FAILURE = 'USER_MODULE_USER_LOGOUT_FAILURE';

// User-list Module
export const USERLIST_MODULE_GET_ONE_USERLIST_BEGIN = "USERLIST_MODULE_GET_ONE_USERLIST_BEGIN";
export const USERLIST_MODULE_GET_ONE_USERLIST_SUCCESS = "USERLIST_MODULE_GET_ONE_USERLIST_SUCCESS";
export const USERLIST_MODULE_GET_ONE_USERLIST_FAILURE = "USERLIST_MODULE_GET_ONE_USERLIST_FAILURE";
export const USERLIST_MODULE_GET_ALL_USERLISTS_BEGIN = "USERLIST_MODULE_GET_ALL_USERLISTS_BEGIN";
export const USERLIST_MODULE_GET_ALL_USERLISTS_SUCCESS = "USERLIST_MODULE_GET_ALL_USERLISTS_SUCCESS";
export const USERLIST_MODULE_GET_ALL_USERLISTS_FAILURE = "USERLIST_MODULE_GET_ALL_USERLISTS_FAILURE";
export const USERLIST_MODULE_UPSERT_USERLIST_BEGIN = "USERLIST_MODULE_UPSERT_USERLIST_BEGIN";
export const USERLIST_MODULE_UPSERT_USERLIST_SUCCESS = "USERLIST_MODULE_UPSERT_USERLIST_SUCCESS";
export const USERLIST_MODULE_UPSERT_USERLIST_FAILURE = "USERLIST_MODULE_UPSERT_USERLIST_FAILURE";
export const USERLIST_MODULE_UPDATE_USERLIST_BEGIN = "USERLIST_MODULE_UPDATE_USERLIST_BEGIN";
export const USERLIST_MODULE_UPDATE_USERLIST_SUCCESS = "USERLIST_MODULE_UPDATE_USERLIST_SUCCESS";
export const USERLIST_MODULE_UPDATE_USERLIST_FAILURE = "USERLIST_MODULE_UPDATE_USERLIST_FAILURE";
export const USERLIST_MODULE_DELETE_USERLIST_BEGIN = "USERLIST_MODULE_DELETE_USERLIST_BEGIN";
export const USERLIST_MODULE_DELETE_USERLIST_SUCCESS = "USERLIST_MODULE_DELETE_USERLIST_SUCCESS";
export const USERLIST_MODULE_DELETE_USERLIST_FAILURE = "USERLIST_MODULE_DELETE_USERLIST_FAILURE";



// file Module
export const FILE_MODULE_GET_ONE_FILE_BEGIN = "FILE_MODULE_GET_ONE_FILE_BEGIN";
export const FILE_MODULE_GET_ONE_FILE_SUCCESS = "FILE_MODULE_GET_ONE_FILE_SUCCESS";
export const FILE_MODULE_GET_ONE_FILE_FAILURE = "FILE_MODULE_GET_ONE_FILE_FAILURE";
export const FILE_MODULE_GET_ONE_ANALYZE_FILE_BEGIN = "FILE_MODULE_GET_ONE_ANALYZE_FILE_BEGIN";
export const FILE_MODULE_GET_ONE_ANALYZE_FILE_SUCCESS = "FILE_MODULE_GET_ONE_ANALYZE_FILE_SUCCESS";
export const FILE_MODULE_GET_ONE_ANALYZE_FILE_FAILURE = "FILE_MODULE_GET_ONE_ANALYZE_FILE_FAILURE";
export const FILE_MODULE_GET_ALL_FILES_BEGIN = "FILE_MODULE_GET_ALL_FILES_BEGIN";
export const FILE_MODULE_GET_ALL_FILES_SUCCESS = "FILE_MODULE_GET_ALL_FILES_SUCCESS";
export const FILE_MODULE_GET_ALL_FILES_FAILURE = "FILE_MODULE_GET_ALL_FILES_FAILURE";
export const FILE_MODULE_UPSERT_FILE_BEGIN = "FILE_MODULE_UPSERT_FILE_BEGIN";
export const FILE_MODULE_UPSERT_FILE_SUCCESS = "FILE_MODULE_UPSERT_FILE_SUCCESS";
export const FILE_MODULE_UPSERT_FILE_FAILURE = "FILE_MODULE_UPSERT_FILE_FAILURE";
export const FILE_MODULE_UPDATE_FILE_BEGIN = "FILE_MODULE_UPDATE_FILE_BEGIN";
export const FILE_MODULE_UPDATE_FILE_SUCCESS = "FILE_MODULE_UPDATE_FILE_SUCCESS";
export const FILE_MODULE_UPDATE_FILE_FAILURE = "FILE_MODULE_UPDATE_FILE_FAILURE";
export const FILE_MODULE_DELETE_FILE_BEGIN = "FILE_MODULE_DELETE_FILE_BEGIN";
export const FILE_MODULE_DELETE_FILE_SUCCESS = "FILE_MODULE_DELETE_FILE_SUCCESS";
export const FILE_MODULE_DELETE_FILE_FAILURE = "FILE_MODULE_DELETE_FILE_FAILURE";
